include $(CLEAR_VARS)

LOCAL_MODULE := tpm2_simulator
LOCAL_MODULE_TAGS := optional

LOCAL_SRC_FILES := tpm2_simulator
LOCAL_MODULE_PATH := $(TARGET_ROOT_OUT_SBIN)
LOCAL_MODULE_CLASS := EXECUTABLES

include $(BUILD_PREBUILT)
